### ISSUE TITLE
No auto-redeem & mail

### ISSUE THREAD

**Issue by pacobarbe31** [MehdiRtal/MicrosoftRewardsClaimer#2] opened 2022-12-22 19:13 UTC
Hello,

I've the last version of this great MicrosoftRewardsClaimer, thank you again for this great work. I've 6 accounts that farm very well (just one that is blocked actually). Some of my accounts now have points to be redeem (Amazon gift cards in UK), but nothing happend when I launch the script. I have all parameters specified : `python3 MicrosoftRewardsBot.py --emailalerts --redeem --headless --session --fast` :

```
[INFO] everyday : None
[INFO] headless : True
[INFO] session : True
[INFO] error : False
[INFO] fast : True
[INFO] accounts : None
[INFO] proxies : None
[INFO] authproxies : False
[INFO] privacy : False
[INFO] emailalerts : True
[INFO] redeem : True
```

`accounts.json` have goals specified on each account, `email.json` have also all parameters (with 2FA password app). I have no errors in logs : 
```
[LOGS] Logs loaded successfully.

********************xxxxxx@outlook.com********************
[WDM] - Downloading: 100%|██████████| 6.35M/6.35M [00:00<00:00, 95.6MB/s][LOGIN] Logging-in...
[LOGIN] Account already logged in !
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 24488 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completing search of card 1
[DAILY SET] Completing quiz of card 2
[DAILY SET] Completing poll of card 3
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/34
[BING] 2/34
[BING] 3/34
[BING] 4/34
[BING] 5/34
[BING] 6/34
[BING] 7/34
[BING] 8/34
[BING] 9/34
[BING] 10/34
[BING] 11/34
[BING] 12/34
[BING] 13/34
[BING] 14/34
[BING] 15/34
[BING] 16/34
[BING] 17/34
[BING] 18/34
[BING] 19/34
[BING] 20/34
[BING] 21/34
[BING] 22/34
[BING] 23/34
[BING] 24/34
[BING] 25/34
[BING] 26/34
[BING] 27/34
[BING] 28/34
[BING] 29/34
[BING] 30/34
[BING] 31/34
[BING] 32/34
[BING] 33/34
[BING] 34/34
[BING] Finished Desktop and Edge Bing searches !
[LOGIN] Logging-in...
[LOGIN] Account already logged in !
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[BING] Starting Mobile Bing searches...
[BING] 1/20
[BING] 2/20
[BING] 3/20
[BING] 4/20
[BING] 5/20
[BING] 6/20
[BING] 7/20
[BING] 8/20
[BING] 9/20
[BING] 10/20
[BING] 11/20
[BING] 12/20
[BING] 13/20
[BING] 14/20
[BING] 15/20
[BING] 16/20
[BING] 17/20
[BING] 18/20
[BING] 19/20
[BING] 20/20
[BING] Finished Mobile Bing searches !
[POINTS] You have earned 247 points today !
[POINTS] You are now at 24735 points !



[......]



********************xxxxxx@outlook.com********************
[LOGIN] Logging-in...
[LOGIN] Account already logged in !
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 7521 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completing search of card 1
[DAILY SET] Completing quiz of card 2
[DAILY SET] Completing poll of card 3
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...

[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/34
[BING] 2/34
[BING] 3/34
[BING] 4/34
[BING] 5/34
[BING] 6/34
[BING] 7/34
[BING] 8/34
[BING] 9/34
[BING] 10/34
[BING] 11/34
[BING] 12/34
[BING] 13/34
[BING] 14/34
[BING] 15/34
[BING] 16/34
[BING] 17/34
[BING] 18/34
[BING] 19/34
[BING] 20/34
[BING] 21/34
[BING] 22/34
[BING] 23/34
[BING] 24/34
[BING] 25/34
[BING] 26/34
[BING] 27/34
[BING] 28/34
[BING] 29/34
[BING] 30/34
[BING] 31/34
[BING] 32/34
[BING] 33/34
[BING] 34/34
[BING] Finished Desktop and Edge Bing searches !
[LOGIN] Logging-in...
[LOGIN] Account already logged in !
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[BING] Starting Mobile Bing searches...
[BING] 1/20
[BING] 2/20
[BING] 3/20
[BING] 4/20
[BING] 5/20
[BING] 6/20
[BING] 7/20
[BING] 8/20
[BING] 9/20
[BING] 10/20
[BING] 11/20
[BING] 12/20
[BING] 13/20
[BING] 14/20
[BING] 15/20
[BING] 16/20
[BING] 17/20
[BING] 18/20
[BING] 19/20
[BING] 20/20
[BING] Finished Mobile Bing searches !
[POINTS] You have earned 292 points today !
[POINTS] You are now at 7813 points !
```

Maybe the `--headless` script mod can't activate email and auto-redeem ? Or problem is probably based on my environment ? I launch this script in a private server in cloud (ubuntu with 1vcpu and 1gb).

Thank you for your help !

**Comment by dmarts05** [comment] 2022-12-31 00:24
That's interesting. Remove --session parameter, redeem feature is working well on my end. Email alerts only happen when an account gets locked, banned... I will try to add support for other kind of alerts soon.

**Comment by RustyRin** [comment] 2023-01-05 18:42
I am also having issues with auto-redeem and emails.
An account got locked, it said it was going to send and email but I never got it.
```
********************ms_account_email@gmail.com********************
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[EMAIL SENDER] This account has been locked! Sending email...
```

My email config looks like this  

```json
[
  {
    "sender": "my_email@gmail.com",
    "password": "gmail_app_password_here",
    "receiver": "my_email@gmail.com",
    "withdrawal": "true",
    "lock": "true",
    "ban": "true",
    "phoneverification": "true",
    "proxyfail": "true"
  }
]
```

For auto-redeem, idk if I am setting the goal wrong, but it does not seem to be reading that there is a goal at all.
on each account I have tried
```json
{
    "username": "rin.new.spam@gmail.com",
    "password": "apZxogmchKuZfFjkJo7R",
    "goal": "Overwatch Digital Code"
  }
```

I have also changed the goal to "Overwatch Digital Code—200 Coins", but this also did not work.

**Comment by dmarts05** [comment] 2023-01-05 19:41
> I am also having issues with auto-redeem and emails. An account got locked, it said it was going to send and email but I never got it.
> 
> ```
> ********************ms_account_email@gmail.com********************
> [LOGIN] Logging-in...
> [LOGIN] Writing email...
> [LOGIN] Writing password...
> [EMAIL SENDER] This account has been locked! Sending email...
> ```
> 
> My email config looks like this
> 
> ```json
> [
>   {
>     "sender": "my_email@gmail.com",
>     "password": "gmail_app_password_here",
>     "receiver": "my_email@gmail.com",
>     "withdrawal": "true",
>     "lock": "true",
>     "ban": "true",
>     "phoneverification": "true",
>     "proxyfail": "true"
>   }
> ]
> ```
> 
> For auto-redeem, idk if I am setting the goal wrong, but it does not seem to be reading that there is a goal at all. on each account I have tried
> 
> ```json
> {
>     "username": "rin.new.spam@gmail.com",
>     "password": "apZxogmchKuZfFjkJo7R",
>     "goal": "Overwatch Digital Code"
>   }
> ```
> 
> I have also changed the goal to "Overwatch Digital Code—200 Coins", but this also did not work.

Email alerts are working on my end. Have you set up 2FA in that Gmail account? Have you generated an app password for this purpose and put in the json correctly? If your answer is yes to both questions I don't really know how to help you sorry.

For your auto-redeem problem, try disabling headless mode and watch carefully during the auto-redeem process, it is possible that it's not finding you reward (send me a screenshot or video). Remember to put --redeem as a parameter.

**Comment by dmarts05** [comment] 2023-01-06 15:40
> * I have 2FA
> * I have ran it headless and not headless, same results
> * I have also added the arguments `--emailalerts --redeem`
> * I do had app password. Though idk if this is just formatting or not, but Google had it separated into 4 sections of 4 characters. It says to just use all 16, so I copied all 16 and used it. Further, Google also says that the app password was never used.

Please, provide a screenshot or video during the auto-redeem process so I can see what the problem is. Have you configured the app password as Other? Copy the characters without spaces.

**Comment by pacobarbe31** [comment] 2023-01-06 16:41
Sorry for the late, after building a new environment on VPS I actually get emails from blocked accounts.
I think that redeem doesn't work because the parameter --headless was activated and without this parameter I couldn't lauch the script due to an error : 
![image](https://user-images.githubusercontent.com/42996804/211056514-6c6b0432-a709-4833-99e1-73f45db2f3e4.png)

I've found that some people have the same problem, probably because I installed chrome manually (see : [compatibility on VPS](https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/46#issuecomment-1308754863))

I actually try to resolve this error, I will try proposed solutions and I will come back if solution was find for me.

Thank you for your help !

**Comment by dmarts05** [comment] 2023-01-06 17:28
It was all due to an indentation error. Auto-redeem has been fixed in my latest pull request. Update your script and it should work now.

**Comment by dmarts05** [comment] 2023-01-06 17:29
> Sorry for the late, after building a new environment on VPS, with fresh install, I actually get emails from blocked accounts or other emails type.
> 
> I think that **auto redeem feature** doesn't work because the parameter --headless was activated, and without this parameter I couldn't lauch the script due to an error :
> 
> ![image](https://user-images.githubusercontent.com/42996804/211056514-6c6b0432-a709-4833-99e1-73f45db2f3e4.png)
> 
> I've found that some people have the same problem, probably because I installed chrome manually (see : [compatibility on VPS](https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/46#issuecomment-1308754863))
> 
> I actually try to resolve this error, I will try proposed solutions and I will come back if solution was find for me.
> 
> Thank you for your help !

You need headless mode for a VPS, check my latest pull request, auto-redeem is fixed now.

**Comment by pacobarbe31** [comment] 2023-01-06 17:49
> > Sorry for the late, after building a new environment on VPS, with fresh install, I actually get emails from blocked accounts or other emails type.
> > I think that **auto redeem feature** doesn't work because the parameter --headless was activated, and without this parameter I couldn't lauch the script due to an error :
> > ![image](https://user-images.githubusercontent.com/42996804/211056514-6c6b0432-a709-4833-99e1-73f45db2f3e4.png)
> > I've found that some people have the same problem, probably because I installed chrome manually (see : [compatibility on VPS](https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/46#issuecomment-1308754863))
> > I actually try to resolve this error, I will try proposed solutions and I will come back if solution was find for me.
> > Thank you for your help !
> 
> You need headless mode for a VPS, check my latest pull request, auto-redeem is fixed now.

You're the best ! thank you for your help, it was the indentation ! Thanks for this fix :)

**Closed** 2023-01-07 11:42 UTC

**Comment by RustyRin** [comment] 2023-01-07 15:44
> > * I have 2FA
> > * I have ran it headless and not headless, same results
> > * I have also added the arguments `--emailalerts --redeem`
> > * I do had app password. Though idk if this is just formatting or not, but Google had it separated into 4 sections of 4 characters. It says to just use all 16, so I copied all 16 and used it. Further, Google also says that the app password was never used.
> 
> Please, provide a screenshot or video during the auto-redeem process so I can see what the problem is. Have you configured the app password as Other? Copy the characters without spaces.

I know its closed now, it is not that big of deal.
But the script just doesn't seem to really recognize that redeem is on.
The only recognition of it is at the start of the script
This was with `--headless --redeem --emailalerts`
```
[INFO] everyday : None
[INFO] headless : True
[INFO] session : False
[INFO] error : False
[INFO] fast : False
[INFO] accounts : None
[INFO] proxies : None
[INFO] authproxies : False
[INFO] privacy : False
[INFO] emailalerts : True
[INFO] redeem : True
```

I never again see anything in the terminal about redeeming.

For emails, there is no space.
`qwertyuiopasdfgh` kinda looking
Only thing is that I have the same address for sending and receiving, for self email.
I have changed it to a different receiver email, but really only been able to test it when an account gets locked or banned. Which has yet to happen since editing it.
